packages:
  - api
  - backend
  - bootstrap
  - cooklang
  - frontend

allowBuilds:
  '@parcel/watcher': false
  bcrypt: false
  esbuild: false
  unrs-resolver: false
  wasm-pack: false

trustPolicy: no-downgrade
trustPolicyExclude:
  - 'chokidar@4.0.3'
