packages:
  - api
  - backend
  - bootstrap
  - cooklang
  - frontend

ignoredBuiltDependencies:
  - '@parcel/watcher'
  - bcrypt
  - esbuild
  - unrs-resolver
  - wasm-pack

trustPolicy: no-downgrade
