[package]
name = "cooklang-wasm"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
cooklang = "0.17.0"
wasm-bindgen = "0.2.100"
serde_json = "1.0.143"

[profile.release]
lto = true
