[package]
name = "cooklang-wasm"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
cooklang = "0.17.1"
wasm-bindgen = "0.2.105"
serde_json = "1.0.145"

[profile.release]
lto = true
