[package]
name = "cooklang-wasm"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
cooklang = "0.15.0"
wasm-bindgen = "0.2.87"
serde_json = "1"

[build-dependencies]
wasm-pack = "0.13.1"
